### ISSUE TITLE
newAppeals not iterable

### ISSUE THREAD

**Issue by salgozino** [kleros/court-notifications-bot#29]
`TypeError: newAppeals is not iterable\n    at module.exports (/home/ubuntu/court-notifications-bot/src/bots/court.js:137:26)`

**Comment by salgozino** [comment]
```
2024-04-03T15:24:11: {
    "err": {
        "type": "TypeError",
        "message": "eventLogs is not iterable",
        "stack": "TypeError: eventLogs is not iterable\n    at formatTokenMovementEvents (/home/ubuntu/court-notifications-bot/src/bots/court.js:312:21)\n    at module.exports (/home/ubuntu/court-notifications-bot/src/bots/court.js:154:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    },
    "msg": "Something went wrong with the bot"
}
```

**Comment by salgozino** [comment]
This errors are in the logs of the xDAI court notification bot at least since March 3rd 2024.
After this error, the bot restart and keep working from the previous block of the last run. Seems that is a random error from the RPC because with the same block requet, this error sometimes happens and sometimes not.

This is not preventing the bot to move forward

**Comment by salgozino** [comment]
The error happen when the newAppeals has the value:
```{ code: 503,
  message: 'server unavailable',
  id: null,
  blockNumber: undefined,
  transactionIndex: undefined,
  logIndex: undefined,
  returnValues: Result {},
  event: undefined,
  signature: null,
  raw: { data: '', topics: [] } }```
